version: '3.8'

services:
  ai-trainer:
    build: 
      context: ..  # Set context to parent directory
      dockerfile: ai_deployment/Dockerfile
    runtime: nvidia
    environment:
      - DISPLAY=:99
      - PARALLEL_INSTANCES=4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../ai_source:/app/ai_source
      - ../results:/app/results

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ai_results
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 