# check powershell
if(WIN32)
    find_program(POWERSHELL_PATH powershell)
    if(NOT POWERSHELL_PATH)
        message(STATUS "Powershell not found - some features may be limited")
    else()
        message(STATUS "Found powershell: ${POWERSHELL_PATH}")
    endif()
else()
    set(USE_POWERSHELL FALSE)
endif() 